(function(){"remove"in Element.prototype||(Element.prototype.remove=function(){this.length?this.map(function(c){c.parentNode&&c.parentNode.removeChild(c)}):this.parentNode&&this.parentNode.removeChild(this)});Element.prototype.css=function(c){var g;if("string"==typeof c)return this.style[c];for(var n in c)g=c[n],"string"!=typeof g&&(g+="px"),this.style[n]=g;return this};Element.prototype.resize=document.resize=function(c){console.log("ok")};Element.prototype.attr=function(c){if("string"==typeof c)return this.getAttribute(c);
for(var g in c)this.setAttribute(g,c[g]);return!0};Element.prototype.show=function(c){arguments.length||(c="block");this.style.display=c};Element.prototype.hide=function(){this.style.display="none"};Element.prototype.height=function(){return this.offsetHeight};Element.prototype.width=function(){return this.offsetWidth};Element.prototype.html=function(c){if(c)this.innerHTML=c;else return this.innerHTML};Element.prototype.val=function(c){if("undefined"!=typeof c)this.value=c;else return this.value};
Element.prototype.crec=function(){return this.getBoundingClientRect()};var h;h=new function(){var c=this;this.version="1.8.3";if(!window.Worker)return c.ready=function(){document.addEventListener("DOMContentLoaded",function(){document.body.innerHTML="<h1><b style='color:#000;padding:10px;'>You are using bad browser! What's wrong with you, man!???</b></h1>"})},!1;var g=function(a,b){for(var f,d,c,e,g=-1,k,h,n,u,t,p,m,v,q="",w="",l="",r=0;r<a.length;r++)f=a[r],m?t?'"'==f?(h=!h,!h&&u.length&&(f={},f[u]=
w,u="",d.attr(f)),w=""):h?w+=f:e||">"==f?">"==f&&(m=0,e?(d&&d.parentNode&&(d=d.parentNode),k?c.parentNode&&(c=c.parentNode):k=1,g=0):d&&/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i.test(d.tagName)&&(d=d.parentNode),e=0):"/"==f?e=1:/[^a-z0-9_]/i.test(f)||(u+=f):p?/[ >]/.test(f)?(p=0,t=1,u="",d=document.createElement(l),n&&c?c.appendChild(d):c=n=d,">"==f&&(m=0),l=""):l+=f:/[a-z0-9_]/i.test(f)&&(p=1,l=f):v?t?(l+=a[r-1],b[l].insertIn(d),v=0):"}"==a[r+1]?t=1:l+=f:"<"==f?(m=1,l="",q.length&&
d&&(d.appendChild(document.createTextNode(q)),q=""),/[a-z0-9_]/i.test(a[r+1])?(t=0,g?c=d:g++,k=0):"/"==a[r+1]&&(e=1)):"{"==f?(v=1,t=0,l="",q.length&&d&&(d.appendChild(document.createTextNode(q)),q="")):q+=f;return n};c.ready=function(a){document.addEventListener("DOMContentLoaded",a)};var n=[],k={},h=0,p,m;c.sel=function(a,b){var f;if("object"==typeof a)return a===document?document:a instanceof Element?a:a.el;f="#"==a[0]?document.getElementById(a.substr(1)):document.querySelectorAll(a);b&&f.length&&
(f=f[0]);return f.length||f instanceof Element?f:!1};c.onwindow=function(a,b){window.addEventListener(a,b)};c.forg=function(a,b){if(b)k[a]&&k[a].forEach(function(a){b(a)});else return k[a]};var e=function(a){a?a.temp||n.push(this):a={};a.getSelf&&a.getSelf(this);this.id=++h;this.state={};this.data={};this.eltype=a.eltype?a.eltype:"div";this.el=document.createElement(this.eltype);a.extend&&this.extend(a.extend);if(a.state)for(var b in a.state)"class"==b?this.state["class"]=a.state[b]:this.state[b]=
a.state[b];if(a.attrs)for(b in a.attrs)p={},p[b]=a.attrs[b],"value"==b?this.state.val=a.attrs[b]:this.state[b]=a.attrs[b],this.el.attr(p);a.groups&&(this.groups=m=a.groups,(p=k[m])?k[m].push(this):k[m]=[this]);"function"==typeof a.chapi&&(this.chapi=a.chapi);a.init?(this.init=a.init,this.init()):a.initLater&&(this.init=a.initLater);a.data&&(this.data=a.data);a.events&&this.addEvents(a.events)};e.prototype.parentEl=!1;e.prototype.insertIn=function(a){a=c.sel(a,1);a.appendChild(this.el);this.parentEl=
a;return this.render()};e.prototype.insertAs=function(a){this.el=c.sel(a,1);return this.render({})};e.prototype.change=function(a,b){var c={},d=0;if(b&&this.chapi&&a)this.chapi(a);else{for(var e in a)this.state[e]=a[e],c[e]=!0,["html","text","val","class"].indexOf(e)+1&&d++;if(d)this.render(c);else return this}};e.prototype.hasClass=function(a){var b=this.state["class"];if(b&&b.length)a=b?b.indexOf(a)+1:!1;else return!1;return a?a:!1};e.prototype.addClass=function(a){if(this.hasClass(a))return!1;
var b=this.state["class"];"string"==typeof b&&b.length&&(b=b.split(" "));b?b.push(a):b=[a];this.change({"class":b});return!0};e.prototype.removeClass=function(a){if(a=this.hasClass(a)){var b=this.state["class"];b&&(b.splice(a-1),this.change({"class":b}));return!0}return!1};e.prototype.eventsArr=[];e.prototype.intervalArr=[];e.prototype.interval=function(a,b){this.intervalArr.push(setInterval(a,b))};e.prototype.clearIntervals=function(){this.intervalArr.forEach(function(a){clearInterval(a)})};e.prototype.timeoutArr=
[];e.prototype.timeout=function(a,b){this.timeoutArr.push(setTimeout(a,b))};e.prototype.clearTimeouts=function(){this.timeoutArr.forEach(function(a){clearTimeout(a)})};e.prototype.remove=function(){this.el.remove();this.removed=!0;this.clearIntervals();return!0};e.prototype.replaceWith=function(a,b){"string"==typeof a?a=b?g(a):document.createTextNode(a):"el"in a&&(a=a.el);this.el.parentNode.replaceChild(a,this.el)};e.prototype.parse=function(a,b){var c=g(a,b);this.el=c;c.attr("class")&&(this.state["class"]=
c.attr("class"));return this};e.prototype.extend=function(a){for(var b in a)"events"==b?this.addEvents(a[b]):this[b]=a[b]};e.prototype.addEvents=function(a){for(var b in a)this.eventsArr.push(b),this["on"+b]=a[b],this.el.addEventListener(b,this["on"+b])};e.prototype.DClist=function(a){var b=this;b.change({html:""});a.map(function(a){a.insertIn(b)});return b};e.prototype.render=function(a){var b=this.state;a?("html"in a&&(this.el.innerHTML=b.html),"text"in a&&(this.el.textContent=b.text),"val"in a&&
(this.el.value=b.val),"class"in a&&(a=b["class"],a="string"==typeof a?a:a.join(" "),this.el.attr({"class":a}))):(b.html&&b.html!=this.el.innerHTML&&(this.el.innerHTML=b.html),b.text&&b.text!=this.el.textContent&&(this.el.textContent=b.text),b.val&&b.val!=this.el.value&&(this.el.value=b.val),b["class"]&&(a=b["class"],a="string"==typeof a?a:a.join(" "),this.el.attr({"class":a})));return this};c.make=function(a){"function"==typeof a&&(a=a());return new e(a)};c.temp=function(a){"function"==typeof a&&
(a=a());"undefined"==typeof a&&(a={});a.temp=1;return new e(a)};c.module=function(){var a=function(b,c){b?a.loaded[b]=c:console.log("loaded module have wrong structure")};a.loaded={};a.run=function(b,c){var d=c.data,e=c.ready;a.loaded[b]?(d||(d={}),d=a.loaded[b](d),a.loaded[b]=d,e&&e(d.dc,d.api)):c.err&&c.err('module "'+b+'" not loaded')};return a}();c.load=function(){var a=c.module.loaded,b,e=function(d){function e(){c.temp({eltype:"script",attrs:{src:g+".js"},events:{load:function(){c.module.run(f,
d);this.remove()},error:function(){d.err&&d.err('module "'+f+"\" can't be loaded")}}}).insertIn(document.head)}var f=d.name,g=b+f;if(a[f]&&!d.force)if(d.exist){var h=a[f];d.exist(h.dc,h.api)}else d.err&&d.err('module "'+f+'" already loaded. Use `force` to load it again');else d.start&&d.start(),d.css?c.temp({eltype:"link",attrs:{rel:"stylesheet",href:b+"css/"+f+".css"},events:{load:function(){e()},error:function(a){d.err&&d.err('css for module "'+f+"\" can't be loaded")}}}).insertIn(document.head):
e()};e.config=function(a){a.src&&(b=a.src)};return e}()};window.DC=h;window.$=h.sel})();