(function(){"remove"in Element.prototype||(Element.prototype.remove=function(){this.length?this.map(function(c){c.parentNode&&c.parentNode.removeChild(c)}):this.parentNode&&this.parentNode.removeChild(this)});Element.prototype.css=function(c){var e;if("string"==typeof c)return this.style[c];for(var h in c)e=c[h],"string"!=typeof e&&(e+="px"),this.style[h]=e;return this};Element.prototype.resize=document.resize=function(c){console.log("ok")};Element.prototype.attr=function(c){if("string"==typeof c)return this.getAttribute(c);
for(var e in c)this.setAttribute(e,c[e]);return!0};Element.prototype.show=function(c){arguments.length||(c="block");this.style.display=c};Element.prototype.hide=function(){this.style.display="none"};Element.prototype.height=function(){return this.offsetHeight};Element.prototype.width=function(){return this.offsetWidth};Element.prototype.html=function(c){if(c)this.innerHTML=c;else return this.innerHTML};Element.prototype.val=function(c){if(c)this.value=c;else return this.value};Element.prototype.crec=
function(){return this.getBoundingClientRect()};var k;k=new function(){var c=this;this.version="1.8.2";if(!window.Worker)return c.ready=function(){document.addEventListener("DOMContentLoaded",function(){document.body.innerHTML="<h1><b style='color:#000;padding:10px;'>You are using bad browser! What's wrong with you, man!???</b></h1>"})},!1;var e=function(a,b){for(var f,c,d,e,g=-1,k,h,m,t,r,n,u,v,p="",w="",l="",q=0;q<a.length;q++)f=a[q],u?r?'"'==f?(h=!h,!h&&t.length&&(f={},f[t]=w,t="",c.attr(f)),w=
""):h?w+=f:e||">"==f?">"==f&&(u=0,e?(c&&c.parentNode&&(c=c.parentNode),k?d.parentNode&&(d=d.parentNode):k=1,g=0):c&&/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i.test(c.tagName)&&(c=c.parentNode),e=0):"/"==f?e=1:/[^a-z0-9_]/i.test(f)||(t+=f):n?/[ >]/.test(f)?(n=0,r=1,t="",c=document.createElement(l),m&&d?d.appendChild(c):d=m=c,">"==f&&(u=0),l=""):l+=f:/[a-z0-9_]/i.test(f)&&(n=1,l=f):v?r?(l+=a[q-1],b[l].insertIn(c),v=0):"}"==a[q+1]?r=1:l+=f:"<"==f?(u=1,l="",p.length&&c&&(c.appendChild(document.createTextNode(p)),
p=""),/[a-z0-9_]/i.test(a[q+1])?(r=0,g?d=c:g++,k=0):"/"==a[q+1]&&(e=1)):"{"==f?(v=1,r=0,l="",p.length&&c&&(c.appendChild(document.createTextNode(p)),p="")):p+=f;return m};c.ready=function(a){document.addEventListener("DOMContentLoaded",a)};var h=[],g={},k=0,m,n;c.sel=function(a,b){var c;if("object"==typeof a)return a===document?document:a instanceof Element?a:a.el;c="#"==a[0]?document.getElementById(a.substr(1)):document.querySelectorAll(a);b&&c.length&&(c=c[0]);return c.length||c instanceof Element?
c:!1};c.onwindow=function(a,b){window.addEventListener(a,b)};c.forg=function(a,b){if(b)g[a]&&g[a].forEach(function(a){b(a)});else return g[a]};var d=function(a){a?a.temp||h.push(this):a={};a.getSelf&&a.getSelf(this);this.id=++k;this.state={};this.data={};this.eltype=a.eltype?a.eltype:"div";this.el=document.createElement(this.eltype);a.extend&&this.extend(a.extend);if(a.state)for(var b in a.state)"class"==b?this.state["class"]=a.state[b]:this.state[b]=a.state[b];if(a.attrs)for(b in a.attrs)m={},m[b]=
a.attrs[b],"value"==b?this.state.val=a.attrs[b]:this.state[b]=a.attrs[b],this.el.attr(m);a.groups&&(this.groups=n=a.groups,(m=g[n])?g[n].push(this):g[n]=[this]);"function"==typeof a.chapi&&(this.chapi=a.chapi);a.init?(this.init=a.init,this.init()):a.initLater&&(this.init=a.initLater);a.events&&this.addEvents(a.events)};d.prototype.parentEl=!1;d.prototype.insertIn=function(a){a=c.sel(a,1);a.appendChild(this.el);this.parentEl=a;return this.render()};d.prototype.insertAs=function(a){this.el=c.sel(a,
1);return this.render({})};d.prototype.change=function(a,b){var c={},d=0;if(b&&this.chapi&&a)this.chapi(a);else{for(var e in a)this.state[e]=a[e],c[e]=!0,["html","text","val","class"].indexOf(e)+1&&d++;if(d)this.render(c);else return this}};d.prototype.hasClass=function(a){var b=this.state["class"];if(b&&b.length)a=b?b.indexOf(a)+1:!1;else return!1;return a?a:!1};d.prototype.addClass=function(a){if(this.hasClass(a))return!1;var b=this.state["class"];"string"==typeof b&&b.length&&(b=b.split(" "));
b?b.push(a):b=[a];this.change({"class":b});return!0};d.prototype.removeClass=function(a){if(a=this.hasClass(a)){var b=this.state["class"];b&&(b.splice(a-1),this.change({"class":b}));return!0}return!1};d.prototype.eventsArr=[];d.prototype.intervalArr=[];d.prototype.interval=function(a,b){this.intervalArr.push(setInterval(a,b))};d.prototype.clearIntervals=function(){this.intervalArr.forEach(function(a){clearInterval(a)})};d.prototype.timeoutArr=[];d.prototype.timeout=function(a,b){this.timeoutArr.push(setTimeout(a,
b))};d.prototype.clearTimeouts=function(){this.timeoutArr.forEach(function(a){clearTimeout(a)})};d.prototype.remove=function(){this.el.remove();this.removed=!0;this.clearIntervals();return!0};d.prototype.replaceWith=function(a,b){"string"==typeof a?a=b?e(a):document.createTextNode(a):"el"in a&&(a=a.el);this.el.parentNode.replaceChild(a,this.el)};d.prototype.parse=function(a,b){var c=e(a,b);this.el=c;c.attr("class")&&(this.state["class"]=c.attr("class"));return this};d.prototype.extend=function(a){for(var b in a)"events"==
b?this.addEvents(a[b]):this[b]=a[b]};d.prototype.addEvents=function(a){for(var b in a)this.eventsArr.push(b),this["on"+b]=a[b],this.el.addEventListener(b,this["on"+b])};d.prototype.DClist=function(a){var b=this;b.change({html:""});a.map(function(a){a.insertIn(b)});return b};d.prototype.render=function(a){var b=this.state;a?("html"in a&&(this.el.innerHTML=b.html),"text"in a&&(this.el.textContent=b.text),"val"in a&&(this.el.value=b.val),"class"in a&&(a=b["class"],a="string"==typeof a?a:a.join(" "),
this.el.attr({"class":a}))):(b.html&&b.html!=this.el.innerHTML&&(this.el.innerHTML=b.html),b.text&&b.text!=this.el.textContent&&(this.el.textContent=b.text),b.val&&b.val!=this.el.value&&(this.el.value=b.val),b["class"]&&(a=b["class"],a="string"==typeof a?a:a.join(" "),this.el.attr({"class":a})));return this};c.make=function(a){"function"==typeof a&&(a=a());return new d(a)};c.temp=function(a){"function"==typeof a&&(a=a());"undefined"==typeof a&&(a={});a.temp=1;return new d(a)}};window.DC=k;window.$=
k.sel})();